import re
from playwright.sync_api import Playwright, sync_playwright, expect

# changed def name accordingly to pytest, removed call for the function in comparison with autogenerated code
def test_add_todo(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://demo.playwright.dev/todomvc/#/")
    page.get_by_role("textbox", name="What needs to be done?").click()
    page.get_by_role("textbox", name="What needs to be done?").fill("1st playwright script")
    page.get_by_role("textbox", name="What needs to be done?").press("Enter")
    page.get_by_role("checkbox", name="Toggle Todo").check()

    # ---------------------
    context.close()
    browser.close()



